### PR TITLE
Move exceptions into thriftrw.errors.

### PR DESCRIPTION
**Pull request by abhinav**
Will put the exception for unrecognized exceptions support here too.

@blampe @breerly @junchaowu

### CODE REVIEW

**Comment by blampe** [comment]
sure

**Comment by breerly** [comment]
:+1:

**Comment by breerly** [comment]
This is a breaking change no? Exceptions are public api.

**Comment by abhinav** [comment]
Most of those exceptions are 'startup' exceptions. They're raised at import time (because you`load` at import time). The protocol exceptions could count as breaking. I'll add that to the changelog.

**Comment by breerly** [comment]
thanks :shipit: - make sure this goes out as a minor and not a patch

**Comment by abhinav** [comment]
Of course. It'll go in 0.5.

**Pull request merged**
