### PR TITLE
allow sending strings as binary

### LINKED ISSUE #29: can't round-trip strings as binary
```python
@pytest.mark.parametrize('s, val, out', [
    (b'foo', b'foo', b'foo'),
    ('foo', b'foo', b'foo'),
    (u'foo', b'foo', b'foo'),
])
def test_text_round_trip_binary(s, val, out):
    if out is None:
        out = s

    wire_val = BinaryTypeSpec.to_wire(s)
    assert wire_val == BinaryValue(val)
    assert BinaryTypeSpec.from_wire(wire_val) == out
```
```
tests/spec/test_primitive.py:55: in test_text_round_trip_binary
    wire_val = BinaryTypeSpec.to_wire(s)
thriftrw/spec/primitive.py:67: in to_wire
    check.instanceof_surface(self, value)
thriftrw/spec/check.py:55: in instanceof_surface
    instanceof_class(type_spec, type_spec.surface, value)
thriftrw/spec/check.py:61: in instanceof_class
    'Cannot serialize %r into a "%s".' % (value, type_spec.name)
E   TypeError: Cannot serialize u'foo' into a "binary".
```
@junchaowu @breerly @kriskowal

### PR DESCRIPTION
**Pull request by blampe**
Resolves #29

### CODE REVIEW

**Comment by breerly** [comment]
Looks good - fix Py3 and :shipit:

**Comment by blampe** [comment]
@abhinav can you drop some py3 wisdom?

**Comment by abhinav** [comment]
The default primitive type spec doesn't do any conversion. It just expects valid input. You need to do something like `_TextTypeSpec` to add custom behavior there. You need to convert the non-binary value into a binary.

**Comment by blampe** [comment]
Abandoning this. I was able to fix my issue by correctly casting unicode strings to binary.

**Pull request closed without merging**
