### PR TITLE
Added cython to installation requirements

### PR DESCRIPTION
**Pull request by webmaven**

### CODE REVIEW

**Comment by abhinav** [comment]
Cython isn't an installation requirement for thriftrw. It's a dev requirement. You can install and use the library without cython because the cython-generated C code is available in the sdist.

**Comment by webmaven** [comment]
Ah, OK, thanks for explaining.

**Comment by webmaven** [comment]
Hmm, but cython is in `requirements.txt`, not `requirements-dev.txt`, and setup.py doesn't have a `dev_requires` or `build_requires`...

**Comment by abhinav** [comment]
Ah, cython is in the requirements because ReadTheDocs needs it there to be able to build the package from source to generate the docstrings.

**Comment by webmaven** [comment]
Couldn't that be solved with a `docs_require`?

**Comment by abhinav** [comment]
Are you sure that's a valid parameter? It's not mentioned in the docs http://pythonhosted.org/setuptools/setuptools.html.

**Comment by webmaven** [comment]
It isn't, but you can make it work in a couple of ways. For example like this:

```
docs_require = [
    'cython',
]
  
# Install requirements for documentation if it's run by ReadTheDocs.org
if os.environ.get('READTHEDOCS'):
    install_requires.extend(docs_require)
```

**Comment by abhinav** [comment]
I don't think that'll work. Cython needs to be available when setup.py is run, not after. The C code is generated when setup.py is executed if Cython was available. Otherwise, it expects the C code to exist already (which it does in case of sdist).

**Comment by webmaven** [comment]
Ah. Hmm. I suppose this wouldn't work either, then, for the same reason?:

```
docs_require = install_requires + ['cython']

setup(
    name='thriftrw',
    ...
    install_requires=install_requires,
    extras_require={
          'docs': docs_require})
```

**Comment by abhinav** [comment]
Correct. One way to make this work would be to have a separate requirements-docs.txt and point ReadTheDocs to that (I just discovered that that's an option in RTD). But after some thought, I disagree that requirements.txt shouldn't contain cython. When you have a fresh checkout of the repo, you expect to be able to do `pip install -r requirements.txt` and have things just work. Moving it to requirements-dev/requirements-docs.txt takes that away.

**Comment by webmaven** [comment]
But the original change I proposed here (adding cython to `install_requires`) still isn't appropriate?

Presumably when you have a fresh checkout of the repository, you want to be able to do `setup.py install` and have things just work as well?

**Comment by abhinav** [comment]
No, because cython is still not a runtime dependency of this library. If you install this package from PyPI for example, you don't need cython to use it; the generated C code is available in the source distribution on PyPI. You need cython only to generate the C code yourself -- when you're working on a fresh checkout of the repository.

**Comment by webmaven** [comment]
But that's what I asked about: 
- make a fresh checkout
- `setup.py install`

**Comment by abhinav** [comment]
For development purposes, the workflow is:

* check out the code
* create and activate a virtualenv
* `pip install -r requirements.txt`
* To run tests, first,

        pip install -r requirements-test.txt

  Then, either

      python setup.py build_ext --inplace
      make test

  Or,

      python setup.py install
      make test

**Comment by webmaven** [comment]
So, you're saying that, for a fresh checkout, `pip install` is a necessary prerequisite to successfully installing using `setup.py install` in all cases?

ISTM that there *ought* to be a way to get `setup.py install` workflows to 'just work' without using `pip install` first.

**Comment by abhinav** [comment]
Not quite. `cython` is an external tool that generates code for this library. For development, it's not unreasonable to expect external tools to already be installed. You don't expect the thrift compiler to be `setup.py install`-able if your library depends on that. The only difference between cython and another external tool here is that `cython` happens to be `pip install`-able, so people sometimes end up listing it as an actual dependency even though its concerns end once the C code is generated.

**Comment by webmaven** [comment]
@abhinav:
>  For development, it's not unreasonable to expect external tools to already be installed.

Then what is the purpose of `setup.py`'s `dev_requires`?

**Comment by blampe** [comment]
@webmaven @abhinav are we just disagreeing over workflow philosophy? Would it help to document the recommended steps for dev or @webmaven is there a particular issue you're experiencing because of this?

**Comment by webmaven** [comment]
It is possible we're just disagreeing over WF philosophy. I am not experiencing any particular issue except confusion (documenting a confusing procedure would help, but I'd rather it was just less confusing).

Essentially, I think a WF that requires using `setup.py` *and* `pip install` is subtly broken. So, even if the workflows duplicate functionality, it ought to be possible to get 'pure' `setup.py` and `pip install` workflows working for both installation and for development.

**Comment by abhinav** [comment]
I agree that the workflow is not straightforward. I have documented it in #100.

About improving the workflow: Adding `cython` to `install_requires` is the wrong solution for it. Maybe it could be added to `extras_require` under the `dev` name, but it would still require `pip`. I'm not aware of a way to do the `python setup.py develop` equivalent of `pip install pkgname[someextra]`.

**Comment by webmaven** [comment]
@abhinav, I'll see what I can come up with.

**Pull request closed without merging**
