### PR TITLE
Expose .thrift file source under __thrift_source__ in generated modules.

### LINKED ISSUE #66: Attach thrift files to service object
Would be nice to be able to access the .thrift files from the service object

### PR DESCRIPTION
**Pull request by abhinav**
Resolves #66.

### CODE REVIEW

**Comment by abhinav** [comment]
@blampe @breerly @junchaowu

**Comment by breerly** [comment]
I like it. :shipit: 

aside - what happens with includes? this is after everything was concatenated?

**Comment by abhinav** [comment]
No. Each included module has its own source code.

Like, if you include foo.thrift in bar.thrift, `bar.foo.__thrift_source__` is the source code for foo.thrift.

**Comment by breerly** [comment]
Thanks for the clarification.

:ship: :it:

**Pull request merged**
