### PR TITLE
Implement include-as syntax.

### LINKED ISSUE #75: Include-as syntax
When including other thrift file, the name of the reference in the thrift file is determined by the base name of the included file.

    include "foo/shared.thrift"

Types defined in shared.thrift will be referenced via `shared`, like `shared.SomeType`.

This makes it impossible to include two files in different folders with the same base names.

    include "foo/shared.thrift"
    include "bar/shared.thrift"

The fix for this is to implement the include-as syntax we discussed previously.

    include x "foo/shared.thrift"
    include y "bar/shared.thrift"

Definitions inside foo/shared.thrift may now be referenced via `x.Something` and similarly, definitions in bar/shared.thrift may be referenced via `y.SomethingElse`.

---

Note that this is a change in syntax that will make Thrift files that use this incompatible with Apache Thrift.

### PR DESCRIPTION
**Pull request by abhinav**
Resolves #75.

One of the tests depends on #90 so it's commented out until I merge that in and rebase this.

### CODE REVIEW

**Comment by abhinav** [comment]
@blampe @breerly @junchaowu

**Comment by kriskowal** [comment]
Let’s hide this behind a flag.

**Comment by abhinav** [comment]
Added feature flag. Disabled by default.

**Comment by blampe** [comment]
NOOOOOOOO NEVER FORK

**Comment by abhinav** [comment]
Removed from docs as discussed

**Comment by blampe** [comment]
lgtm

**Pull request merged**
