### PR TITLE
Add __thrift_module__ to struct, union, and enum

### PR DESCRIPTION
**Pull request by breerly**
solves #22 

- [x] impl
- [x] tests
- [x] docs

cc @abhinav @blampe

### CODE REVIEW

**Comment by breerly** [comment]
will add tests in a bit

**Comment by breerly** [comment]
@abhinav think there should be a test here? I don't feel strongly either way since it's just a dundr link and there is no actual behavior.

**Comment by abhinav** [comment]
LGTM

**Comment by breerly** [comment]
I'll merge once the build passes :)

**Pull request merged**
